from pathlib import Path

import pandas as pd
import openpyxl
from openpyxl.styles import Font


# ============================================================
# PATH CONFIGURATION
# ============================================================

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parents[2]

# Model output generated by the categorization experiment.
MODEL_FILE = SCRIPT_DIR / "SingleLabel.xlsx"

# Manually annotated ground-truth file.
MANUAL_FILE = PROJECT_ROOT / "data" / "categorie_manuali.csv"

# Validation results are stored in the current experiment directory.
OUTPUT_FILE = SCRIPT_DIR / "SingleLabel_Evaluation.xlsx"


# ============================================================
# DATA LOADING
# ============================================================

print("Loading files...")

df_modello = pd.read_excel(MODEL_FILE)

try:
    df_manuale = pd.read_csv(
        MANUAL_FILE,
        sep=None,
        engine="python",
        on_bad_lines="skip",
        encoding="utf-8-sig"
    )
    print(f"Successfully loaded '{MANUAL_FILE.name}'.")

except Exception as error:
    raise RuntimeError(
        f"Unable to load the manual annotation file: {MANUAL_FILE}"
    ) from error


# Remove accidental whitespace from column names.
df_modello.columns = df_modello.columns.str.strip()
df_manuale.columns = df_manuale.columns.str.strip()


# ============================================================
# DATA PREPARATION
# ============================================================

# Create a normalized key based on the evidence text.
df_modello["EVIDENZA_CLEAN"] = (
    df_modello["EVIDENZA"]
    .astype(str)
    .str.strip()
    .str.lower()
)

df_manuale["EVIDENZA_CLEAN"] = (
    df_manuale["EVIDENZA"]
    .astype(str)
    .str.strip()
    .str.lower()
)


# Normalize the name of the manually assigned category column.
if "CATEGORIA_MANUALE" in df_manuale.columns:
    df_manuale = df_manuale.rename(
        columns={"CATEGORIA_MANUALE": "CATEGORIA_CORRETTA"}
    )

elif "CATEGORIA" in df_manuale.columns:
    df_manuale = df_manuale.rename(
        columns={"CATEGORIA": "CATEGORIA_CORRETTA"}
    )


# ============================================================
# DATA MERGE
# ============================================================

df_merged = df_modello.merge(
    df_manuale[["EVIDENZA_CLEAN", "CATEGORIA_CORRETTA"]],
    on="EVIDENZA_CLEAN",
    how="inner",
)


# ============================================================
# VALIDATION
# ============================================================

if not df_merged.empty:

    def calcola_esito(row):
        gt = str(row["CATEGORIA_CORRETTA"]).strip().upper()
        p1 = str(row["CATEGORIA_PRINCIPALE"]).strip().upper()
        p2 = str(row["CATEGORIA_SECONDARIA"]).strip().upper()

        if gt == p1:
            return "MATCH_PRIMARIO"

        elif gt == p2:
            return "MATCH_SECONDARIO"

        elif p1 in ["ERRORE_FORMATO", "ERRORE_CRITICO"]:
            return "ERRORE_MODELLO"

        else:
            return "NON_COINCIDE"


    df_merged["ESITO"] = df_merged.apply(calcola_esito, axis=1)


    # ========================================================
    # METRICS
    # ========================================================

    totale = len(df_merged)

    match_primario = len(
        df_merged[df_merged["ESITO"] == "MATCH_PRIMARIO"]
    )

    match_secondario = len(
        df_merged[df_merged["ESITO"] == "MATCH_SECONDARIO"]
    )

    errori_modello = len(
        df_merged[df_merged["ESITO"] == "ERRORE_MODELLO"]
    )

    non_coincide = len(
        df_merged[df_merged["ESITO"] == "NON_COINCIDE"]
    )

    # Top-1 accuracy: correct primary category.
    accuracy_top1 = (
        match_primario / totale
        if totale > 0
        else 0
    )

    # Additional matches obtained through the secondary category.
    accuracy_top2 = (
        match_secondario / totale
        if totale > 0
        else 0
    )

    # Overall Top-2 accuracy: primary + secondary matches.
    accuracy_totale = (
        (match_primario + match_secondario) / totale
        if totale > 0
        else 0
    )


    # ========================================================
    # VALIDATION REPORT
    # ========================================================

    print("\n" + "=" * 50)
    print("             VALIDATION REPORT")
    print("=" * 50)

    print(f"Total sampled evidence items:      {totale}")
    print(f"Top-1 Accuracy:                    {accuracy_top1:.2%}")
    print(f"Secondary Match Increment:         {accuracy_top2:.2%}")
    print(f"Overall Top-2 Accuracy:            {accuracy_totale:.2%}")

    print("-" * 50)

    print("Match details:")
    print(f"  - Correct primary categories:    {match_primario}")
    print(f"  - Correct secondary categories:  {match_secondario}")
    print(f"  - Complete mismatches:            {non_coincide}")
    print(f"  - LLM output errors:              {errori_modello}")

    print("=" * 50)


    # ========================================================
    # SAVE RESULTS
    # ========================================================

    output_file = OUTPUT_FILE

    df_merged.to_excel(output_file, index=False)

    wb = openpyxl.load_workbook(output_file)
    ws = wb.active


    # ========================================================
    # EMBEDDED REPORT
    # ========================================================

    report_data = [
        ["SUMMARY", "RESULTS"],
        ["PRIMARY MATCH", match_primario],
        ["SECONDARY MATCH", match_secondario],
        ["MISMATCHES", non_coincide],
        ["TOTAL EVIDENCE", totale],
        ["Top-1 Accuracy", f"{accuracy_top1:.2%}"],
        ["Top-2 Increment", f"{accuracy_top2:.2%}"],
        ["TOTAL TOP-2 ACCURACY", f"{accuracy_totale:.2%}"],
        ["MODEL ERROR", errori_modello],
    ]

    # Write the validation summary to columns J and K.
    for r_idx, row in enumerate(report_data, 1):
        ws.cell(row=r_idx, column=10, value=row[0])
        ws.cell(row=r_idx, column=11, value=row[1])

    # Apply simple formatting to the report header.
    ws.cell(row=1, column=10).font = Font(bold=True)
    ws.cell(row=1, column=11).font = Font(bold=True)

    wb.save(output_file)

    print(
        f"\nValidation results saved to "
        f"'{output_file.name}'."
    )


else:
    print(
        "Error: unable to match model predictions with the manual "
        "annotations. Verify that the values in the 'EVIDENZA' column "
        "refer to the same evidence items."
    )