import pandas as pd
import openpyxl
from pathlib import Path
from openpyxl.styles import Font


# ---------------------------------------------------------------------
# PATHS
# ---------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parents[2]

# Model output generated by the categorization experiment.
MODEL_FILE = SCRIPT_DIR / "SingleLabel.xlsx"

# Manually annotated ground-truth file.
MANUAL_FILE = PROJECT_ROOT / "data" / "categorie_manuali.csv"

# Validation results are stored in the current experiment directory.
OUTPUT_FILE = SCRIPT_DIR / "SingleLabel_Evaluation.xlsx"


print("Loading files...")


# ---------------------------------------------------------------------
# DATA LOADING
# ---------------------------------------------------------------------

df_modello = pd.read_excel(MODEL_FILE)
df_manuale = pd.read_csv(
    MANUAL_FILE,
    sep=None,
    engine="python",
    on_bad_lines="skip",
    encoding="utf-8-sig"
)

print("Files loaded successfully.")


# Remove accidental whitespace from column names.
df_modello.columns = df_modello.columns.str.strip()
df_manuale.columns = df_manuale.columns.str.strip()


# Create a normalized merge key based on the evidence text.
df_modello['EVIDENZA_CLEAN'] = (
    df_modello['EVIDENZA']
    .astype(str)
    .str.strip()
    .str.lower()
)

df_manuale['EVIDENZA_CLEAN'] = (
    df_manuale['EVIDENZA']
    .astype(str)
    .str.strip()
    .str.lower()
)


# Normalize the ground-truth category column name.
if 'CATEGORIA_MANUALE' in df_manuale.columns:
    df_manuale = df_manuale.rename(
        columns={'CATEGORIA_MANUALE': 'CATEGORIA_CORRETTA'}
    )

elif 'CATEGORIA' in df_manuale.columns:
    df_manuale = df_manuale.rename(
        columns={'CATEGORIA': 'CATEGORIA_CORRETTA'}
    )


# ---------------------------------------------------------------------
# DATA MERGE
# ---------------------------------------------------------------------

df_merged = df_modello.merge(
    df_manuale[['EVIDENZA_CLEAN', 'CATEGORIA_CORRETTA']],
    on='EVIDENZA_CLEAN',
    how='inner'
)


if not df_merged.empty:

    # -----------------------------------------------------------------
    # EVALUATION LOGIC
    # -----------------------------------------------------------------

    def calcola_esito(row):
        gt = str(row['CATEGORIA_CORRETTA']).strip().upper()
        p1 = str(row['CATEGORIA_PRINCIPALE']).strip().upper()
        p2 = str(row['CATEGORIA_SECONDARIA']).strip().upper()

        if gt == p1:
            return 'MATCH_PRIMARIO'

        elif gt == p2:
            return 'MATCH_SECONDARIO'

        elif p1 in ['ERRORE_FORMATO', 'ERRORE_CRITICO']:
            return 'ERRORE_MODELLO'

        else:
            return 'NON_COINCIDE'


    df_merged['ESITO'] = df_merged.apply(
        calcola_esito,
        axis=1
    )


    # -----------------------------------------------------------------
    # METRICS
    # -----------------------------------------------------------------

    totale = len(df_merged)

    match_primario = len(
        df_merged[df_merged['ESITO'] == 'MATCH_PRIMARIO']
    )

    match_secondario = len(
        df_merged[df_merged['ESITO'] == 'MATCH_SECONDARIO']
    )

    errori_modello = len(
        df_merged[df_merged['ESITO'] == 'ERRORE_MODELLO']
    )

    non_coincide = len(
        df_merged[df_merged['ESITO'] == 'NON_COINCIDE']
    )


    accuracy_top1 = (
        match_primario / totale
        if totale > 0 else 0
    )

    accuracy_top2 = (
        match_secondario / totale
        if totale > 0 else 0
    )

    accuracy_totale = (
        (match_primario + match_secondario) / totale
        if totale > 0 else 0
    )


    # -----------------------------------------------------------------
    # VALIDATION REPORT
    # -----------------------------------------------------------------

    print("\n" + "=" * 45)
    print("             VALIDATION REPORT")
    print("=" * 45)

    print(f"Total sampled evidence:             {totale}")
    print(f"Primary accuracy (Top-1):           {accuracy_top1:.2%}")
    print(f"Secondary recovery (Top-2 increment): {accuracy_top2:.2%}")
    print(f"Overall accuracy (Top-2 total):     {accuracy_totale:.2%}")

    print("-" * 45)

    print("Match details:")
    print(f"  - Exact primary matches:          {match_primario}")
    print(f"  - Secondary matches:              {match_secondario}")
    print(f"  - Complete mismatches:            {non_coincide}")
    print(f"  - LLM output errors:              {errori_modello}")

    print("=" * 45)


    # -----------------------------------------------------------------
    # SAVE RESULTS
    # -----------------------------------------------------------------

    output_file = OUTPUT_FILE

    df_merged.to_excel(
        output_file,
        index=False
    )


    # Add the summary report to columns J and K.
    wb = openpyxl.load_workbook(output_file)
    ws = wb.active


    report_data = [
        ["SUMMARY", "RESULTS"],
        ["PRIMARY MATCH", match_primario],
        ["SECONDARY MATCH", match_secondario],
        ["MISMATCHES", non_coincide],
        ["TOTAL EVIDENCE", totale],
        ["Top-1 Accuracy", f"{accuracy_top1:.2%}"],
        ["Top-2 Increment", f"{accuracy_top2:.2%}"],
        ["TOTAL TOP-2 ACCURACY", f"{accuracy_totale:.2%}"],
        ["MODEL ERROR", errori_modello]
    ]


    # Write the report to columns J (10) and K (11).
    for r_idx, row in enumerate(report_data, 1):
        ws.cell(
            row=r_idx,
            column=10,
            value=row[0]
        )

        ws.cell(
            row=r_idx,
            column=11,
            value=row[1]
        )


    # Bold report headers.
    ws.cell(row=1, column=10).font = Font(bold=True)
    ws.cell(row=1, column=11).font = Font(bold=True)


    wb.save(output_file)

    print(
        f"\nEvaluation file generated successfully: "
        f"'{output_file}'"
    )


else:
    print(
        "Error: unable to match the datasets. "
        "Check that the EVIDENZA texts are identical in both files."
    )